### ISSUE TITLE
Some custom attributes are searching for tf2utils when it's already installed

### ISSUE THREAD

**Issue by nocwed** [nosoop/SM-TFCustomAttributeStarterPack#63] opened 2022-06-03 03:43 UTC
So i'm trying to use this attributes but they keep searching for tf2utils and I don't know if it's supposed to happen or I'm using the wrong version.

```custom-attr-starter-pack\addcond_while_active.smx ([TF2] Custom Attribute: addcond while active): Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\airblast_projectiles_adds_self_condition.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\alt_fire_throws_cleaver.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\attr_group_overheal_uber.smx ([TF2CA] Medigun Uber: Group Overheal): Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\attr_nailgun_slow.smx ([TF2CA] TF2 Classic Nailgun Slow): Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\condition_stack_on_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\crossbow_addcond_on_teammate_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\damage_increase_on_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\explosive_shield_bash.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\full_clip_refill_after_time.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\jar_is_bleed_on_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\joke_medigun_mod_drain_health.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\low_gravity_charge.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\lunchbox_effects\sugar_frenzy.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\lunchbox_override_pickup_type.smx: Error detected in plugin startup (see error logs)
custom-attr-starter-pack\minigun_radial_buff.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\mod_crit_type_vs_condition.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\mvm_attributes.smx ([TF2] Custom Attribute: MvM Attributes): Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\projectile_heal_on_teammate_contact.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\reload_full_clip_at_once.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\shake_on_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\syringegun_poison_on_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\tag_last_enemy_hit.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\weapon_overheat.smx: Could not find required plugin "nosoop_tf2utils"
custom-attr-starter-pack\weapon_rate_buff_ally.smx: Could not find required plugin "nosoop_tf2utils"```

**Comment by nosoop** [comment] 2022-06-03 03:46
Hi, thanks for the report &mdash; please check your error logs to see if [TF2 Utils](https://github.com/nosoop/SM-TFUtils) failed to load in any way.

**Comment by nocwed** [comment] 2022-06-03 04:51
TF2Utils is loaded and i've already double checked that I have every dependency installed.

**Comment by nosoop** [comment] 2022-06-03 05:15
Are you checking if it's loaded using `sm plugins load tf2utils`?  Plugin load failures on startup get it into a weird state where it isn't actually loaded in.  If it successfully loaded, then you may need to restart your server or manually reload the dependencies.

If you're still running into issues, please attach drag and drop the most recent `addons/sourcemod/logs/errors_*.log` file.

**Comment by nosoop** [comment] 2022-06-18 12:38
I'm unable to reproduce this issue; closing this since there isn't anything actionable for me here.  If you're still having problems after a server restart, please do reopen the issue with more information for me to work with (preferably providing the information requested in the template).  SourceMod's definitely finicky when it comes to plugins that don't load correctly the first time.

If you're using a TF2 Utils version older than 0.18.0.1 on Windows (which was about 4 days old when this issue was created), you will want to update; you may have run into nosoop/SM-TFUtils#4, which would also cause the cascading failures.

**Closed by nosoop** 2022-06-18 12:38 UTC
Labels: install help
