### ISSUE TITLE
attr_buff_override Error

### ISSUE THREAD

**Issue by ctf2w-crafting** [nosoop/SM-TFCustomAttributeStarterPack#30] opened 2020-07-01 00:17 UTC
```
L 06/30/2020 - 14:25:12: [SM] Exception reported: Client 16 is not in game
L 06/30/2020 - 14:25:12: [SM] Blaming: customweaponstf/custom-attribute-adapter/attr_buff_override.smx
L 06/30/2020 - 14:25:12: [SM] Call stack trace:
L 06/30/2020 - 14:25:12: [SM]   [0] IsPlayerAlive
L 06/30/2020 - 14:25:12: [SM]   [1] Line 129, D:\TF2 Testing Server\steamapps\common\Team Fortress 2 Dedicated Server\tf\addons\sourcemod\scripting\attr_buff_override.sp::OnPulseRageBuffPre
```

**Comment by nosoop** [comment] 2020-07-01 00:21
Duplicate of #27.

**Closed by nosoop** 2020-07-01 00:21 UTC
Labels: bug
